let lastReading = "";

export default function handler(req, res) {
  const readings = [
    "Los hilos del destino comienzan a moverse. Algo se teje en silencio tras las sombras.",
    "Hoy no estás donde estabas ayer, y aún así sigues ignorando el verdadero motivo de tu cambio.",
    "Una presencia olvidada ronda tu energía. Tal vez no viniste solo hasta aquí.",
    "El universo ha guardado silencio demasiado tiempo. Esta noche, algo se atreve a hablar.",
    "Una puerta se entreabre en tu vida. No todos podrán verla. No todos deberían cruzarla.",
    "Te han estado observando... y no con ojos físicos. Una decisión tuya pronto tendrá eco.",
    "El corazón te susurra verdades que la razón calla. Ignorarlas es seguir andando a ciegas.",
    "Una señal te ha sido enviada. La reconocerás por su rareza. No la ignores.",
    "No se trata de suerte. Algo dentro de ti está despertando.",
    "No es casualidad. Esa persona no regresó sin motivo.",
    "Tu intuición está siendo afinada por algo que no entiendes... todavía.",
    "Hoy alguien hablará sin palabras. Presta atención a lo que no se dice.",
    "Un ciclo se cierra, pero su eco aún resuena. No actúes como si ya estuviera resuelto.",
    "Has llegado al borde de una verdad. Saltar no es obligatorio, pero quedarse costará.",
    "Lo que temes perder... quizá nunca fue realmente tuyo.",
    "Esa sensación que se repite no es paranoia. Es advertencia.",
    "Pronto se te ofrecerá una segunda oportunidad. No llegará de la forma que esperas.",
    "Hoy, el universo te da permiso para abandonar lo que te desgasta.",
    "Tu versión más poderosa aún no ha hablado. Pero ya respira en ti.",
    "Lo que sueñas esta noche no es un sueño. Es mensaje.",
    "Tu mente busca lógica. Tu alma ya entendió.",
    "Una sombra del pasado ha vuelto, disfrazada de coincidencia.",
    "No esperes señales del cielo si cierras los ojos cada vez que brillan.",
    "Estás más cerca de la verdad cuando aceptas que no todo debe ser comprendido.",
    "Hoy no hagas ruido. El universo solo habla en silencio.",
    "Lo que sientes que falta… puede que nunca haya existido. Pero eso no lo hace menos real.",
    "Eres el último eslabón de una historia que no recuerdas. Pero que ya estás terminando.",
    "Lo que el azar te ofrece hoy... lleva escrito tu nombre desde hace siglos.",
    "Tu fuerza no se mide en lo que aguantas, sino en lo que decides soltar.",
    "Has sido guiado hasta aquí para romper un ciclo. Pero aún no sabes cuál.",
    "Esa inquietud que sientes no es miedo. Es memoria.",
    "El silencio de alguien dice más que sus palabras. Hoy, escucha entre líneas.",
    "Hoy se oculta una elección importante tras algo trivial. No mires en línea recta.",
    "Todo cambiará si aceptas ver lo que te incomoda.",
    "La verdad no será cómoda. Pero lo será más que la mentira que repites.",
    "Hoy alguien te revela su verdadera intención. No te sorprendas si ya lo sabías.",
    "Un vínculo invisible une tu energía con la de alguien más. El lazo se tensa.",
    "Lo que decides esta semana afectará más de lo que crees… y a más de una persona.",
    "Una verdad llegará en forma de error. Y será la lección que no sabías necesitar.",
    "Hoy, una parte tuya que creías perdida se activa. Observa tus reacciones.",
    "No huyas de la incomodidad. Ahí es donde se esconde el verdadero mensaje.",
    "Un rostro del pasado volverá, pero no todos verán la misma persona.",
    "Tu futuro ha cambiado sutilmente… por una elección que tomaste sin pensar.",
    "Hay una conexión que está a punto de quebrarse o renacer. Tú decides.",
    "Tus sueños no están rotos. Solo se están reorganizando para volverse reales.",
    "Aquello que no entiendes hoy, mañana será tu bendición o tu advertencia.",
    "Estás a punto de ver algo que no todos ven. No todos están listos. Tú quizás sí.",
    "Lo que se esconde en ti no es debilidad. Es poder que aún no sabes usar.",
    "La energía de alguien más te atraviesa hoy. Si sientes un cambio, no es solo tuyo.",
    "Si dudas... hazlo con el corazón abierto. El miedo no siempre se equivoca, pero el alma tampoco.",
    "No todo lo que brilla te guía… pero algo apagado hoy podría encender tu destino.",
    "Tus certezas están a punto de tambalear. No es el fin, es una nueva visión.",
    "Una energía vieja se resiste a irse. Tal vez debas enfrentarla antes de avanzar.",
    "Te estás acercando demasiado a una verdad que no todo el mundo está dispuesto a aceptar.",
    "No es casualidad que hoy sientas nostalgia. Algo del pasado quiere que lo mires de nuevo.",
    "Te costará soltar lo que ya no vibra contigo. Pero más te costará quedarte.",
    "Hoy podrías recibir una respuesta… pero no será a la pregunta que esperabas.",
    "Una parte de ti se cansó de esperar. Escucha lo que quiere decirte.",
    "Tu sensibilidad no es debilidad. Es tu mejor brújula, aunque a veces duela.",
    "El patrón se repite porque aún no has entendido lo que vino a enseñarte.",
    "Estás por abrir una puerta. Lo que hay detrás no será cómodo, pero será real.",
    "Algo que diste por perdido no estaba roto, solo esperaba otro momento.",
    "Hoy no se trata de tomar decisiones… sino de ver qué las está guiando.",
    "No estás atrapado, solo estás ignorando una salida que no parece obvia.",
    "Esa intuición que negaste volverá hoy con más fuerza. No cometerás el mismo error dos veces.",
    "Alguien no es quien tú pensabas… y eso puede ser el mejor regalo o la peor advertencia.",
    "Tu cuerpo habla antes que tu mente. Escúchalo. Él sabe por dónde comenzar.",
    "Hay una historia que te estás contando… pero no es la historia real.",
    "Estás a punto de vivir una escena que soñaste alguna vez. Recuerda cómo termina.",
    "Tu energía está chocando con la de alguien más. No es culpa tuya, pero sí tu responsabilidad protegerte.",
    "Una conversación pendiente será el inicio de un cambio inevitable.",
    "Si sientes que no encajas, quizá es porque has venido a crear algo nuevo, no a repetir.",
    "Un ciclo está cerrando por dentro, aunque por fuera aún todo parezca igual.",
    "Tu pasado quiere hablarte. No lo interrumpas esta vez.",
    "No subestimes los detalles de hoy. Lo mínimo podría reordenar lo inmenso.",
    "Alguien no dijo lo que sentía. Tú tampoco. Hoy el silencio empieza a hacer ruido.",
    "Una parte de ti está esperando tu permiso para manifestarse. ¿Qué estás reprimiendo?",
    "Estás soñando demasiado pequeño. Lo que viene no cabe en tus planes actuales.",
    "Una emoción que ignoraste volverá con forma de oportunidad. Estás listo.",
    "No hagas promesas hoy. Observa, espera… y decide sin miedo.",
    "El universo te quiere incómodo porque sabe que ahí es donde creces.",
    "No estás equivocado. Solo estás viendo con ojos nuevos algo que antes te cegaba.",
    "Hoy algo cambia por dentro. Nadie lo notará… todavía. Pero tú sí.",
    "Una herida que creías cerrada puede sangrar de nuevo. No huyas. A veces el dolor trae dirección.",
    "Tu alma quiere jugar con el caos. Pero también quiere bailar con la verdad.",
    "Lo que postergas habla más de ti que lo que haces. Hoy, observa qué estás evitando.",
    "Una coincidencia se repetirá. Esta vez, no la tomes a la ligera.",
    "Estás por conocer una versión de ti que no sabías que existía. Prepárate.",
    "La respuesta no está en buscar. Está en dejar de resistirte a lo que ya es.",
    "Un miedo se te revelará como un maestro. ¿Lo escucharás o lo callarás otra vez?",
    "Ese impulso que sientes no es ansiedad. Es un llamado. Uno que no se repetirá igual.",
    "Hoy entenderás por qué tu camino no fue el de los demás. Era porque el tuyo no tenía mapa.",
    "No confundas estabilidad con estancamiento. Lo que no se mueve… muere.",
    "Una mirada, un gesto, una frase. Algo ínfimo hoy activará un cambio mayor.",
    "Tu sombra quiere hablar. No como enemiga, sino como parte olvidada de tu verdad.",
    "Alguien que no esperabas puede volverse clave. Pero no lo sabrás si no estás presente.",
    "Tu zona segura se ha vuelto jaula. Hoy podrías romper un barrote.",
    "No esperes la aprobación de quienes no entienden tu fuego. Avanza.",
    "Esa parte tuya que callaste tanto tiempo… ya no piensa quedarse en silencio.",
    "Hoy puedes elegir: repetir el pasado o renacer con él. Pero no puedes hacer ambas."
  ];

  let randomIndex, selectedReading;

  if (readings.length > 1) {
    do {
      randomIndex = Math.floor(Math.random() * readings.length);
      selectedReading = readings[randomIndex];
    } while (selectedReading === lastReading);
  } else {
    selectedReading = readings[0];
  }

  lastReading = selectedReading;

  res.status(200).json({ reading: selectedReading });
}
